# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/exbiks/ProjectPunisher/ProjectPunisher.cache/wt [current_project]
set_property parent.project_path /home/exbiks/ProjectPunisher/ProjectPunisher.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/exbiks/ProjectPunisher/ProjectPunisher.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/angle_combination.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/angle_normalization.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/angle_normalization_wrapper.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/decoder_type_1.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/decoder_type_2.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/decoder_type_3.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/exponent_operation.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/float_point_adder.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/float_point_multiplier.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/float_point_multiplier_wrapper.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/mult_add.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/rams_sp_rf_rst.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/rams_sp_rom_angle_comb_detail.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/rams_sp_rom_pf1.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/rams_sp_rom_pf2.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/rams_sp_rom_pf3.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/rams_sp_rom_sine_val_exp0.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/rams_sp_rom_sine_val_exp1.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/simple_dual_one_clock.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/sine_calculator_pipelined_2_stage.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/stack.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/state_var_evaluator.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/term_accumulator.sv
  /home/exbiks/BTP/Phase2/BTP/verilog_codes/top_module.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/exbiks/ProjectPunisher/ProjectPunisher.srcs/constrs_1/new/constraint1.xdc
set_property used_in_implementation false [get_files /home/exbiks/ProjectPunisher/ProjectPunisher.srcs/constrs_1/new/constraint1.xdc]


synth_design -top top_module -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
